name: Build and Push Java Image

on:   
 push:
     branches: [develop]
     paths:
      - 'java/**'
 workflow_dispatch:
 
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: my-thai-star-java

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build and push Java image  
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ env.IMAGE_NAME }}
          registry: ghcr.io
          tags: ${GITHUB_RUN_ID}, latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: java/Dockerfile.githubactions
