name: Deploy to Okteto

on:
  schedule:
    - cron:  '0 */4 * * *'
  workflow_dispatch:

jobs:
  deploy:
    if: ${{github.repository == 'devonfw/my-thai-star'}}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: okteto/login@latest
      with:
        token: ${{ secrets.OKTETO_LOGIN_TOKEN }}
        
    - name: "Activate personal namespace"
      uses: okteto/namespace@latest
      with:
        name:  devonfw-core
    
    - name: "Create deployment"
      uses: okteto/apply@latest
      with:
        manifest: k8s.yml
    - name: Sleep for 30 seconds
      uses: jakejarvis/wait-action@v0.1.0
      with:
        time: '30s'        
    - name: Verify
      uses: srt32/uptime@v0.2
      with:
        url-to-hit: "https://mts-devonfw-core.cloud.okteto.net/bookTable"
        expected-statuses: "200"
        
